CREATE TABLE IF NOT EXISTS user (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(10) NOT NULL,
    photo LONGTEXT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'GUEST',
    PRIMARY KEY(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS store (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    slogan VARCHAR(240) NOT NULL,
    banner LONGTEXT NULL,
    admin_id BIGINT NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY (admin_id) REFERENCES user(id)
) ENGINE=InnoDB;
